### ISSUE TITLE
Slack's approval-handler lambda is broken in recent versions

### ISSUE THREAD

**Issue by BDQ** [cloudcomponents/cdk-constructs#39]
Hi All,
After a recent version bump of `cdk-codepipeline-slack` to `1.0.58` the `approval-handler` lambda is failing with the following error:

![image](https://user-images.githubusercontent.com/22470/84662730-1bde9480-af14-11ea-8459-34566d556285.png)

I'm going to try upgrading to more recent versions to see if this is still an issue.

**Comment by asterikx** [comment]
This _might_ be related to #33.

**Comment by SqueezeToyAliens** [comment]
The issue is related to changes in recent versions of express that make an import start(i.e., import * as <name>) not to import the default object when bundled.

The file where the problem resides:
![image](https://user-images.githubusercontent.com/18571677/86297511-38611900-bc04-11ea-868a-88ec1062eaa3.png)

The exception is thrown here:
![image](https://user-images.githubusercontent.com/18571677/86297562-57f84180-bc04-11ea-8775-389df20d9c48.png)

When using Parcel, the resulted object for this import statement is not express' "createServer" function, rather, an object with all the exported members of the module.

The object contains a **default** field, which is what's needed.

Using **import express from "express"** will solve the bug(instead of using **import *** syntax).

A simple way to reproduce the issue and check the bug-fix is:
- Create an empty directory
- 'cd' into the directory
- Type _yarn init -y_
- Install the required dependencies with _yarn add express@4.17.1 @types/express@4.17.6 parcel@2.0.0-beta.1_

- Create two .ts files - the first you can name 'express-import-star.ts'. Paste the following two lines into the file:
import * as express from "express";
express();

- Create a second .ts file named 'express-import-default.ts'. Paste the following into the file:
import express from "express";
express();

- Now bundle the first file by typing 'yarn parcel build express-import-start.ts', then execute the resulting .js script with 'node index.js'(default out file name for parcel)

You'll notice the exception mentioned above:
![image](https://user-images.githubusercontent.com/18571677/86298613-cfc76b80-bc06-11ea-8a9c-66fbe7148ddf.png)

- Try to build and execute the second script('express-import-default'):
  - Type _yarn parcel build express-import-default.ts_
  - Type _node index.js_

No error appears.
